const char ca_ecdsa_crt[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBnDCCAUOgAwIBAgIUQBIFJHsvGYCDazwHmnfwDAuLeGkwCgYIKoZIzj0EAwIw\r\n"
"JDEiMCAGA1UEAwwZTXlFQ0RTQSBDQSB3ZXB0ZWNoLWlvdC5kZTAeFw0yNTA0MTYx\r\n"
"NDE2NDlaFw0zNTA0MTQxNDE2NDlaMCQxIjAgBgNVBAMMGU15RUNEU0EgQ0Egd2Vw\r\n"
"dGVjaC1pb3QuZGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATzxlPhkp3e5WTQ\r\n"
"IMnCegImS5T2zfykS4tH6VR94657ODCPNiZeC5F4ALTQwSsCA2+lfbKyW/RxnGqE\r\n"
"mc8RQJzIo1MwUTAdBgNVHQ4EFgQUkNEjc9t6IHwFJq2ABdZfkupkbpkwHwYDVR0j\r\n"
"BBgwFoAUkNEjc9t6IHwFJq2ABdZfkupkbpkwDwYDVR0TAQH/BAUwAwEB/zAKBggq\r\n"
"hkjOPQQDAgNHADBEAiAfaIo46Ym8LSk7SSU6bHsK2qUgHxzA6sZ3/270WuZMzwIg\r\n"
"B4C/Yj2gyXdC8X7orZKRj6eUazmRXYkmqbu9HcuGrUE=\r\n"
"-----END CERTIFICATE-----\r\n"
;
const size_t ca_ecdsa_crt_len = 631;
