const char ca_ecdsa_crt[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBnDCCAUOgAwIBAgIUM9JJ0rKX8qxtxQMJvaF9gkVwh98wCgYIKoZIzj0EAwIw\r\n"
"JDEiMCAGA1UEAwwZTXlFQ0RTQSBDQSB3ZXB0ZWNoLWlvdC5kZTAeFw0yNTA1MjYw\r\n"
"NjU3NDNaFw0zNTA1MjQwNjU3NDNaMCQxIjAgBgNVBAMMGU15RUNEU0EgQ0Egd2Vw\r\n"
"dGVjaC1pb3QuZGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARaqSnhSUO8/OI2\r\n"
"6JTbwu3YCl6h3Z2AIjbkq20KlsGbIAUUq26/C8pdDNWOR52NYfyMUnnjR6t5EbuN\r\n"
"AsH9s71oo1MwUTAdBgNVHQ4EFgQUItyXbxCULwm3UfIUdzjKQ/cAoW8wHwYDVR0j\r\n"
"BBgwFoAUItyXbxCULwm3UfIUdzjKQ/cAoW8wDwYDVR0TAQH/BAUwAwEB/zAKBggq\r\n"
"hkjOPQQDAgNHADBEAiB4ePdO47PBAtWoikyKbSHV1MfAJHl2Yx9O9b/JKYwOnwIg\r\n"
"Gck150RUZAhiY5xqYyfmQqg9dGbtIPLoHC5b4vyhDbM=\r\n"
"-----END CERTIFICATE-----\r\n"
;
const size_t ca_ecdsa_crt_len = 631;
