const char ca_ecdsa_crt[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBnDCCAUOgAwIBAgIUSQxteXmDPZgSPPDdSa1Io4ztxGAwCgYIKoZIzj0EAwIw\r\n"
"JDEiMCAGA1UEAwwZTXlFQ0RTQSBDQSB3ZXB0ZWNoLWlvdC5kZTAeFw0yNTA1Mjcx\r\n"
"MjA5NTNaFw0zNTA1MjUxMjA5NTNaMCQxIjAgBgNVBAMMGU15RUNEU0EgQ0Egd2Vw\r\n"
"dGVjaC1pb3QuZGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAScFj4Lxe9bfB3z\r\n"
"SmTaB0flphFT6G/0w3HUYY9GkBOMe40Nht1NKcFUO1d2mlJTbn88gQL7oTw9iFqL\r\n"
"pdt1czFjo1MwUTAdBgNVHQ4EFgQUdUoTlR2Tt59Aj+foJxz+iDlfISAwHwYDVR0j\r\n"
"BBgwFoAUdUoTlR2Tt59Aj+foJxz+iDlfISAwDwYDVR0TAQH/BAUwAwEB/zAKBggq\r\n"
"hkjOPQQDAgNHADBEAiAGBg1OgN3sCI4eRriK2e8Orna2IsfPUFLoc84F7OttNQIg\r\n"
"aCuX+BNuipL7SDjuE2HfMH8MfR2+D9qgqUbsF+VPuuw=\r\n"
"-----END CERTIFICATE-----\r\n"
;
const size_t ca_ecdsa_crt_len = 631;
